### ISSUE TITLE
[预算外请款＆流程审批] Btici交易所NFT流动性补充申请

### ISSUE THREAD

**Issue by mrsunnyy** [Golden-Siv/Sunny#1]

**Comment by mrsunnyy** [comment]
等老板批左后安排退回forpmail (HTX)

**Comment by mrsunnyy** [comment]
Bitci交易所提款尚未成功提出，需要跟进

**Comment by mrsunnyy** [comment]
@Heidiyuen 已跟進

**Comment by mrsunnyy** [comment]
![Image](https://github.com/user-attachments/assets/c36f2a64-8dda-4f2f-8fe6-8ba09b79108e)

**Comment by mrsunnyy** [comment]
@Heidiyuen 請留意一下polo_ace_mm有無收到Bitci既email，應該會係依幾日回覆我地，謝謝

**Comment by Heidiyuen** [comment]
OK but still not receive the email
